[functions]
  external_node_modules = ["express", "mongoose", "express-ejs-layouts"]
  node_bundler = "esbuild"
  included_files = [views/*]

[build]
  command = "npm run build"

[[redirects]]
  force = true
  from = "/*"
  status = 200
  to = "/netlify/functions/server"
